default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: 'username'
      password: 'password'
      host:     <%= ENV['IP'] %>



development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  database: app_production
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
