default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: 'username'
      password: 'password'
      host:     <%= ENV['IP'] %>



development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  database: app_production
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
  username: 'adtscevwafktyp'
  password: '6cd5ded1a454d34ca60fff368a0ef07cf173c3f78d8c8df39e0d944169a53306'